### PR TITLE
swap design fix

### PR DESCRIPTION
**Pull request by luckmer**

### CODE REVIEW

**Review by awojciak — CHANGES_REQUESTED** [review]
1) 
obraz
maybe in this case don't show exchange rate
2) add cursor: pointer on transaction details button, when able to click

**Review by awojciak — CHANGES_REQUESTED** [review]
obraz
maybe don't show exchange rate in this case

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Screenshot from 2022-02-20 14-54-03

There should also by swap loader on unconnected wallet. (It may be already done :D)

**Comment by wojciech-cichocki** [comment]
IMO "No data" shouldn't be displayed at all on price

**Comment by wojciech-cichocki** [comment]
See transaction details should be clickable on disconnected wallet:
Screenshot from 2022-02-20 15-22-54

**Comment by wojciech-cichocki** [comment]
This loader no make sense. After open app - disconnected wallet:
Screenshot from 2022-02-20 18-36-59

**Comment by wojciech-cichocki** [comment]
Loader on exchange ratio disappear:
Screenshot from 2022-02-20 18-45-23

**Comment by wojciech-cichocki** [comment]
IMO: 
Screenshot from 2022-02-20 18-48-11

Slippage tolerance ~~value~~ is the pricing difference between the price at the confirmation time and the actual price of the transaction users are willing to accept when swapping.

**Comment by wojciech-cichocki** [comment]
Balances are hard to read. We need amount prefixes: such as: k, M
Screenshot from 2022-02-20 18-50-10

**Comment by wojciech-cichocki** [comment]
Last issue: It looks strange when the wallet is not connected. Display nothing instead of `Balance: 0.000000000`:
Screenshot from 2022-02-20 19-32-15

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
