### PR TITLE
New design - minor fixes

### PR DESCRIPTION
**Pull request by awojciak**

### CODE REVIEW

**Comment by wojciech-cichocki** [comment]
hover pointer on "MAX" button
Screenshot from 2022-02-16 18-24-19

**Comment by wojciech-cichocki** [comment]
"See transaction details" hover
Screenshot from 2022-02-16 18-34-04

**Comment by wojciech-cichocki** [comment]
1. Open app on swap tab 
2. Select token FROM and TO
3. Go to pool tab
4. black screen and console:
Screenshot from 2022-02-16 18-37-14

**Comment by wojciech-cichocki** [comment]
USDT balance looks ugly
Screenshot from 2022-02-16 18-42-54

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
reverse pair:
Screenshot from 2022-02-16 18-45-08

**Review by PawelKrawczyk96 — APPROVED** [review]

**Review by PawelKrawczyk96 — CHANGES_REQUESTED** [review]
above

**Comment by PawelKrawczyk96** [comment]
image

**Review by PawelKrawczyk96 — APPROVED** [review]

**Pull request merged**
