### PR TITLE
Add interval refresher

### PR DESCRIPTION
**Pull request by p6te**
- added interval refresher to the app.
- handle refresh on timeout error
image
image
image

### CODE REVIEW

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Layout problem:
image

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Please create a new target branch (sync with `dev`), and name it `opt`. We want to make the update atomic

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Refreshing blocks the entire app. What are the options to make it non-blocking?
[Screencast from 13.07.2024 20:56:03.webm](https://github.com/user-attachments/assets/ace5af67-f555-4b6e-a05e-ce2c02343b6d)
video comment: (after triggering the refresh, I want to change the tick index. Actually the tick is updated the moment all the data is loaded (not all of this data is even needed to plot the chart)

**Review by zielvna — APPROVED** [review]

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Why you remove loader from unclaimed fees?

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
