### PR TITLE
fixes in positions views

### PR DESCRIPTION
**Pull request by Makuss88**

### CODE REVIEW

**Review by PawelKrawczyk96 — CHANGES_REQUESTED** [review]
image

wrong text color

**Comment by PawelKrawczyk96** [comment]
image
i don't know how about this approx USD numbers.  i think this should be add in this task

**Review by awojciak — CHANGES_REQUESTED** [review]
1) 
obraz
background color of current price value should be the same as one used in min and max
2) 
obraz
currently we're not shortening values there, but I think now it should be done because font is much bigger than before, do it in similar war as it's done on positions list

**Comment by PawelKrawczyk96** [comment]
image
last thing - magnifier icon is different than figma project.

**Review by PawelKrawczyk96 — APPROVED** [review]

**Pull request merged**
